actions:
  - type: remove
    selector: ".ad-banner"

  - type: replace
    selector: "#header h1"
    newElement: "<h1>🌟 Yeni Başlık</h1>"

  - type: insert
    position: "after"
    target: "main"
    element: "<footer>Vision Bridge ile oluşturuldu</footer>"

  - type: alter
    oldValue: "Machine Learning"
    newValue: "Yapay Zeka"
